### PR TITLE
pyshimmer/bluetooth: add possibility to retrieve battery level (voltage/percent) via bluetooth

### PR DESCRIPTION
**Pull request by Noodlesalat**
In this pull request we add the possibility to retrieve the shimmers battery level (in percent or voltage) via the bluetooth connection. This is a new feature as it is currently not supported by pyshimmer.

### CODE REVIEW

**Comment by lumagi** [comment]
Hey, that's an awesome contribution! Thank you for making the pull request. Please don't be surprised, I changed the target branch from `master` to `develop`.
I only have one request before I merge this: since you added a new command, could you please also write a unit test for it? You can find unit tests for other commands in [test_bt_commands.py](https://github.com/seemoo-lab/pyshimmer/blob/master/test/bluetooth/test_bt_commands.py). Please also add the test there.

**Comment by lumagi** [comment]
@Noodlesalat Do you plan on implementing the unit tests? If not, could you provide a log of the serial interface traffic when executing the command, so I can implement the tests? You can use [interceptty](https://github.com/geoffmeyers/interceptty) for sniffing the connection.

**Comment by Noodlesalat** [comment]
Hi!
Implementing the unit tests is still on our todo list but unfortunately we did not have the time yet. We will keep the task and would like to add the tests at a later point of time.

**Comment by Noodlesalat** [comment]
@lumagi The missing testcases have finally arrived!! :tada: :+1: 

```
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.10.8, pytest-7.1.3, pluggy-1.0.0
rootdir: /mnt/git/pyshimmer
plugins: cov-4.0.0
collected 127 items                                                                                                                                                                                               

test/test_device.py ......................                                                                                                                                                                  [ 17%]
test/test_serial_base.py ..........                                                                                                                                                                         [ 25%]
test/test_util.py ...........                                                                                                                                                                               [ 33%]
test/bluetooth/test_bluetooth_api.py ..................                                                                                                                                                     [ 48%]
test/bluetooth/test_bt_commands.py .......................                                                                                                                                                  [ 66%]
test/bluetooth/test_bt_serial.py .....                                                                                                                                                                      [ 70%]
test/reader/test_binary_reader.py ....                                                                                                                                                                      [ 73%]
test/reader/test_reader_const.py .                                                                                                                                                                          [ 74%]
test/reader/test_shimmer_reader.py ............                                                                                                                                                             [ 83%]
test/reader/test_util.py ..                                                                                                                                                                                 [ 85%]
test/uart/test_dock_api.py ...............                                                                                                                                                                  [ 96%]
test/uart/test_dock_serial.py ....                                                                                                                                                                          [100%]

=============================================================================================== 127 passed in 1.57s ===============================================================================================
```

Thanks for the hint regarding "interceptty". It helped a lot! :slightly_smiling_face:

**Comment by lumagi** [comment]
Great, this looks perfect! Thanks a lot for your effort!

**Pull request merged**
